#!/usr/bin/env python3
"""
Lockfile merge conflict analysis for actions.lock

Tests how git handles merge conflicts in a global lockfile across realistic
development scenarios. Generates synthetic lockfiles matching the format
produced by `gh actions-pin` and measures conflict rates.

Usage:
    python3 lockfile_merge_test.py

Produces a summary table of conflict results across multiple scenario
categories: stress tests, insertion position tests, realistic workflow
names, per-workflow lockfile comparison, and union merge strategy.

Related: https://github.com/github/c2c-actions/pull/10106 (ADR 10032)
"""

import hashlib
import os
import random
import subprocess
import tempfile
import shutil
import sys
from dataclasses import dataclass, field

# ---------------------------------------------------------------------------
# Action catalog
# ---------------------------------------------------------------------------

FIRST_PARTY = [
    "actions/checkout", "actions/setup-node", "actions/setup-python",
    "actions/setup-go", "actions/setup-java", "actions/cache",
    "actions/upload-artifact", "actions/download-artifact",
    "actions/github-script", "actions/labeler", "actions/stale",
    "actions/create-release", "actions/delete-package-versions",
    "actions/attest-build-provenance",
]
THIRD_PARTY = [
    "docker/build-push-action", "docker/setup-buildx-action",
    "docker/login-action", "hashicorp/setup-terraform",
    "azure/login", "aws-actions/configure-aws-credentials",
    "codecov/codecov-action", "peter-evans/create-pull-request",
    "dorny/paths-filter", "ossf/scorecard-action",
]
COMPOSITES = [
    "myorg/shared-actions/lint", "myorg/shared-actions/test",
    "myorg/shared-actions/deploy", "myorg/shared-actions/notify",
]
ALL_ACTIONS = FIRST_PARTY + THIRD_PARTY + COMPOSITES

REALISTIC_WORKFLOW_NAMES = [
    "ci", "cd", "lint", "test", "build", "deploy", "release",
    "codeql", "dependabot-auto-merge", "docker-build", "e2e",
    "greetings", "issue-labeler", "nightly", "pages", "pr-check",
    "publish-npm", "security-scan", "stale", "terraform-plan",
]

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def fake_sha():
    return hashlib.sha1(os.urandom(20)).hexdigest()


def git(repo, *args):
    return subprocess.run(
        ["git", "-c", "commit.gpgsign=false", "-c", "tag.gpgsign=false"]
        + list(args),
        capture_output=True, text=True, cwd=repo,
    )


def init_repo(repo, gitattributes=None):
    git(repo, "init", "-b", "main")
    git(repo, "config", "user.email", "test@test.com")
    git(repo, "config", "user.name", "Test")
    git(repo, "config", "commit.gpgsign", "false")
    if gitattributes:
        with open(os.path.join(repo, ".gitattributes"), "w") as f:
            f.write(gitattributes)


def generate_lockfile(workflows, pool):
    """Generate a lockfile matching gh actions-pin output format."""
    lines = [
        "# This file is machine-generated by `gh actions-pin`.",
        "# Do not edit by hand; run `gh actions-pin` to update.",
        "# Docs: https://gh.io/actions-lockfile",
        "version: v0.0.1",
        "actions:",
    ]
    all_refs = set()
    for deps in workflows.values():
        all_refs.update(deps)
    for ref_str in sorted(all_refs):
        sha = pool[ref_str]
        oid = abs(hash(ref_str.split("/")[0])) % 100000000
        rid = abs(hash(ref_str.split("@")[0])) % 1000000000
        tag = ref_str.split("@")[1]
        branch = f"releases/{tag.split('.')[0]}" if "." in tag else tag
        lines += [
            f"    {ref_str}:sha1-{sha}:",
            f"        tag: {tag}",
            f"        branch: {branch}",
            f"        commit: sha1-{sha}",
            f"        owner_id: {oid}",
            f"        repo_id: {rid}",
        ]
    lines.append("workflows:")
    for wf_path in sorted(workflows.keys()):
        lines.append(f"    {wf_path}:")
        lines.append(f"        dependencies:")
        for dep in sorted(workflows[wf_path]):
            sha = pool[dep]
            lines.append(f"            - {dep}:sha1-{sha}")
    return "\n".join(lines) + "\n"


def generate_per_wf_lockfile(wf_name, deps, pool):
    lines = [f"# Lockfile for {wf_name}", "version: v0.0.1", "dependencies:"]
    for dep in sorted(deps):
        sha = pool[dep]
        lines += [f"    {dep}:sha1-{sha}:", f"        commit: sha1-{sha}"]
    return "\n".join(lines) + "\n"


def gen_base(n, rng):
    wfs, pool, refs = {}, {}, {}
    for action in ALL_ACTIONS:
        ref = (
            "main"
            if action.startswith("myorg")
            else f"v{rng.randint(3,5)}.{rng.randint(0,9)}.{rng.randint(0,5)}"
        )
        refs[action] = ref
        pool[f"{action}@{ref}"] = fake_sha()
    for i in range(1, n + 1):
        path = f".github/workflows/wf-{i:03d}.yml"
        chosen = rng.sample(ALL_ACTIONS, rng.randint(2, 6))
        if "actions/checkout" not in chosen:
            chosen[0] = "actions/checkout"
        wfs[path] = [f"{a}@{refs[a]}" for a in chosen]
    return wfs, pool, refs


# ---------------------------------------------------------------------------
# Mutation helpers
# ---------------------------------------------------------------------------


def add_wfs(wfs, pool, refs, ids):
    for i in ids:
        path = f".github/workflows/wf-{i:03d}.yml"
        chosen = random.sample(ALL_ACTIONS, 3)
        if "actions/checkout" not in chosen:
            chosen[0] = "actions/checkout"
        for a in chosen:
            ref = refs.get(a, "v4.0.0")
            key = f"{a}@{ref}"
            if key not in pool:
                pool[key] = fake_sha()
        wfs[path] = [f"{a}@{refs.get(a, 'v4.0.0')}" for a in chosen]


def repin_wfs(wfs, pool, ids):
    for i in ids:
        path = f".github/workflows/wf-{i:03d}.yml"
        if path in wfs:
            for dep in wfs[path]:
                pool[dep] = fake_sha()


def repin_action(wfs, pool, prefix):
    for key in list(pool.keys()):
        if key.startswith(prefix + "@"):
            pool[key] = fake_sha()


def upgrade(wfs, pool, action, refs, new_ver):
    old_ref = refs.get(action)
    if not old_ref:
        return
    old_key = f"{action}@{old_ref}"
    new_key = f"{action}@{new_ver}"
    pool[new_key] = fake_sha()
    for path in wfs:
        wfs[path] = [new_key if d == old_key else d for d in wfs[path]]


def delete_wfs(wfs, ids):
    for i in ids:
        wfs.pop(f".github/workflows/wf-{i:03d}.yml", None)


# ---------------------------------------------------------------------------
# Scenario runners
# ---------------------------------------------------------------------------


@dataclass
class Result:
    name: str
    desc: str
    conflict: bool
    markers: int = 0
    conflict_files: list = field(default_factory=list)


def write_state(repo, wfs, pool):
    wf_dir = os.path.join(repo, ".github", "workflows")
    os.makedirs(wf_dir, exist_ok=True)
    for f in os.listdir(wf_dir):
        if f.endswith(".yml"):
            os.remove(os.path.join(wf_dir, f))
    with open(os.path.join(wf_dir, "actions.lock"), "w") as f:
        f.write(generate_lockfile(wfs, pool))
    for path, deps in wfs.items():
        full = os.path.join(repo, path)
        with open(full, "w") as f:
            f.write(
                f"name: {os.path.basename(path)}\non: push\njobs:\n"
                f"  build:\n    runs-on: ubuntu-latest\n    steps:\n"
            )
            for d in deps:
                f.write(f"      - uses: {d}\n")


def write_state_per_wf(repo, wfs, pool):
    wf_dir = os.path.join(repo, ".github", "workflows")
    os.makedirs(wf_dir, exist_ok=True)
    for f in os.listdir(wf_dir):
        os.remove(os.path.join(wf_dir, f))
    for path, deps in wfs.items():
        full = os.path.join(repo, path)
        wf_name = os.path.basename(path)
        with open(full, "w") as f:
            f.write(
                f"name: {wf_name}\non: push\njobs:\n"
                f"  build:\n    runs-on: ubuntu-latest\n    steps:\n"
            )
            for d in deps:
                f.write(f"      - uses: {d}\n")
        lock_path = full.replace(".yml", ".lock")
        with open(lock_path, "w") as f:
            f.write(generate_per_wf_lockfile(wf_name, deps, pool))


def run_global_scenario(name, desc, base_wfs, base_pool, refs, mutate_a, mutate_b,
                        gitattributes=None):
    repo = tempfile.mkdtemp(prefix="lf-")
    init_repo(repo, gitattributes=gitattributes)

    write_state(repo, base_wfs, base_pool)
    git(repo, "add", "-A")
    r = git(repo, "commit", "-m", "base")
    if r.returncode != 0:
        shutil.rmtree(repo)
        return None

    git(repo, "checkout", "-b", "branch-a", "main")
    wfs_a = {k: list(v) for k, v in base_wfs.items()}
    pool_a = dict(base_pool)
    mutate_a(wfs_a, pool_a, refs)
    write_state(repo, wfs_a, pool_a)
    git(repo, "add", "-A")
    git(repo, "commit", "-m", "branch-a")

    git(repo, "checkout", "-b", "branch-b", "main")
    wfs_b = {k: list(v) for k, v in base_wfs.items()}
    pool_b = dict(base_pool)
    mutate_b(wfs_b, pool_b, refs)
    write_state(repo, wfs_b, pool_b)
    git(repo, "add", "-A")
    git(repo, "commit", "-m", "branch-b")

    git(repo, "checkout", "branch-a")
    merge = git(repo, "merge", "branch-b", "--no-edit")

    conflict = merge.returncode != 0
    markers = 0
    conflict_files = []
    if conflict:
        lp = os.path.join(repo, ".github", "workflows", "actions.lock")
        if os.path.exists(lp):
            with open(lp) as f:
                markers = f.read().count("<<<<<<<")
        ls = git(repo, "diff", "--name-only", "--diff-filter=U")
        conflict_files = [l.strip() for l in ls.stdout.strip().split("\n") if l.strip()]
        git(repo, "merge", "--abort")

    shutil.rmtree(repo)
    return Result(name, desc, conflict, markers, conflict_files)


def run_per_wf_scenario(name, desc, base_wfs, base_pool, refs, mutate_a, mutate_b):
    repo = tempfile.mkdtemp(prefix="lf-pw-")
    init_repo(repo)

    write_state_per_wf(repo, base_wfs, base_pool)
    git(repo, "add", "-A")
    r = git(repo, "commit", "-m", "base")
    if r.returncode != 0:
        shutil.rmtree(repo)
        return None

    for branch, mutate in [("branch-a", mutate_a), ("branch-b", mutate_b)]:
        git(repo, "checkout", "-b", branch, "main")
        wfs = {k: list(v) for k, v in base_wfs.items()}
        pl = dict(base_pool)
        mutate(wfs, pl, refs)
        write_state_per_wf(repo, wfs, pl)
        for p in set(base_wfs) - set(wfs):
            for ext in [".yml", ".lock"]:
                fp = os.path.join(repo, p.replace(".yml", ext))
                if os.path.exists(fp):
                    os.remove(fp)
        git(repo, "add", "-A")
        git(repo, "commit", "-m", branch)

    git(repo, "checkout", "branch-a")
    merge = git(repo, "merge", "branch-b", "--no-edit")
    conflict = merge.returncode != 0
    conflict_files = []
    if conflict:
        ls = git(repo, "diff", "--name-only", "--diff-filter=U")
        conflict_files = [l.strip() for l in ls.stdout.strip().split("\n") if l.strip()]
        git(repo, "merge", "--abort")

    shutil.rmtree(repo)
    return Result(name, desc, conflict, 0, conflict_files)


# ---------------------------------------------------------------------------
# Print helpers
# ---------------------------------------------------------------------------


def print_header(title):
    print(f"\n{'='*80}")
    print(f"  {title}")
    print(f"{'='*80}\n")


def print_result(r):
    if r is None:
        print("  ⚠️  scenario failed to run")
        return
    icon = "❌" if r.conflict else "✅"
    suffix = ""
    if r.conflict:
        lf_files = [f for f in r.conflict_files if "actions.lock" in f or ".lock" in f]
        wf_files = [f for f in r.conflict_files if f not in lf_files]
        parts = []
        if r.markers:
            parts.append(f"{r.markers} marker(s) in lockfile")
        elif lf_files:
            parts.append(f"{len(lf_files)} lockfile(s)")
        if wf_files:
            parts.append(f"{len(wf_files)} workflow file(s)")
        suffix = f" — {', '.join(parts)}" if parts else ""
    print(f"  {icon} {r.name}{suffix}")
    if r.desc:
        print(f"     {r.desc}")


def print_summary(results, label=""):
    valid = [r for r in results if r is not None]
    clean = sum(1 for r in valid if not r.conflict)
    total = len(valid)
    pct = clean / total * 100 if total else 0
    print(f"\n  {label}Clean: {clean}/{total} ({pct:.0f}%)")


# ---------------------------------------------------------------------------
# Test suites
# ---------------------------------------------------------------------------


def run_stress_tests():
    """100 workflows with wf-NNN naming — worst case for sort collisions."""
    print_header("STRESS TEST — 100 workflows, sequential names (worst case)")

    rng = random.Random(42)
    base_wfs, base_pool, refs = gen_base(100, rng)
    base_lines = len(generate_lockfile(base_wfs, base_pool).split("\n"))
    print(f"  Base: 100 workflows, {base_lines} line lockfile\n")

    scenarios = [
        ("disjoint-adds", "A adds wf 101-105, B adds wf 106-110",
         lambda w, p, r: add_wfs(w, p, r, range(101, 106)),
         lambda w, p, r: add_wfs(w, p, r, range(106, 111))),
        ("disjoint-repins", "A re-pins wf 1-10, B re-pins wf 50-60",
         lambda w, p, r: repin_wfs(w, p, range(1, 11)),
         lambda w, p, r: repin_wfs(w, p, range(50, 61))),
        ("same-action-repin", "Both re-pin actions/checkout → different SHAs",
         lambda w, p, r: repin_action(w, p, "actions/checkout"),
         lambda w, p, r: repin_action(w, p, "actions/checkout")),
        ("mixed-realistic", "A: +3wf repin 5 | B: +2wf -3wf repin 3",
         lambda w, p, r: (add_wfs(w, p, r, range(101, 104)), repin_wfs(w, p, range(1, 6))),
         lambda w, p, r: (add_wfs(w, p, r, range(104, 106)),
                          delete_wfs(w, [20, 30, 40]), repin_wfs(w, p, range(60, 63)))),
        ("overlapping-deletes", "A dels wf 10,20,30,40,50 | B dels wf 30,40,50,60,70",
         lambda w, p, r: delete_wfs(w, [10, 20, 30, 40, 50]),
         lambda w, p, r: delete_wfs(w, [30, 40, 50, 60, 70])),
        ("different-upgrades", "A upgrades checkout→v5, B upgrades setup-node→v5",
         lambda w, p, r: upgrade(w, p, "actions/checkout", r, "v5.0.0"),
         lambda w, p, r: upgrade(w, p, "actions/setup-node", r, "v5.0.0")),
        ("both-add-same-wf", "Both add wf-101 with different deps",
         lambda w, p, r: add_wfs(w, p, r, [101]),
         lambda w, p, r: add_wfs(w, p, r, [101])),
        ("massive-repin", "A re-pins ALL actions, B adds 10 new wfs",
         lambda w, p, r: [p.__setitem__(k, fake_sha()) for k in list(p.keys())],
         lambda w, p, r: add_wfs(w, p, r, range(101, 111))),
    ]

    results = []
    for name, desc, fn_a, fn_b in scenarios:
        r = run_global_scenario(name, desc, base_wfs, base_pool, refs, fn_a, fn_b)
        results.append(r)
        print_result(r)

    print_summary(results)
    return results


def run_insertion_position_tests():
    """Test how insertion position affects merge conflicts."""
    print_header("INSERTION POSITION — where new entries sort matters")

    actions = ["actions/checkout@v4.0.0", "actions/setup-node@v4.0.0",
               "actions/cache@v4.0.0"]
    pool = {a: fake_sha() for a in actions}
    base_wfs = {}
    for c in "abcdefghijklmnopqrst":
        base_wfs[f".github/workflows/{c}.yml"] = [random.choice(actions)]
    refs = {}

    scenarios = [
        ("both-append-end", "Both add at end (u.yml + v.yml)",
         lambda w, p, r: w.__setitem__(".github/workflows/u.yml", ["actions/checkout@v4.0.0"]),
         lambda w, p, r: w.__setitem__(".github/workflows/v.yml", ["actions/setup-node@v4.0.0"])),
        ("end-vs-middle", "One at end (u.yml), one in middle (j2.yml)",
         lambda w, p, r: w.__setitem__(".github/workflows/u.yml", ["actions/checkout@v4.0.0"]),
         lambda w, p, r: w.__setitem__(".github/workflows/j2.yml", ["actions/setup-node@v4.0.0"])),
        ("different-middles", "Both in different middles (c2.yml + p2.yml)",
         lambda w, p, r: w.__setitem__(".github/workflows/c2.yml", ["actions/checkout@v4.0.0"]),
         lambda w, p, r: w.__setitem__(".github/workflows/p2.yml", ["actions/setup-node@v4.0.0"])),
        ("adjacent-middles", "Both adjacent in middle (j1.yml + j2.yml)",
         lambda w, p, r: w.__setitem__(".github/workflows/j1.yml", ["actions/checkout@v4.0.0"]),
         lambda w, p, r: w.__setitem__(".github/workflows/j2.yml", ["actions/setup-node@v4.0.0"])),
        ("modify-diff-ends", "Modify different workflows (a.yml + t.yml)",
         lambda w, p, r: w.__setitem__(".github/workflows/a.yml", ["actions/cache@v4.0.0"]),
         lambda w, p, r: w.__setitem__(".github/workflows/t.yml", ["actions/cache@v4.0.0"])),
        ("modify-adjacent", "Modify adjacent workflows (j.yml + k.yml)",
         lambda w, p, r: w.__setitem__(".github/workflows/j.yml",
                                       ["actions/cache@v4.0.0", "actions/checkout@v4.0.0"]),
         lambda w, p, r: w.__setitem__(".github/workflows/k.yml",
                                       ["actions/cache@v4.0.0", "actions/checkout@v4.0.0"])),
        ("delete-different", "Delete different workflows (c.yml + q.yml)",
         lambda w, p, r: w.pop(".github/workflows/c.yml"),
         lambda w, p, r: w.pop(".github/workflows/q.yml")),
    ]

    results = []
    for name, desc, fn_a, fn_b in scenarios:
        r = run_global_scenario(name, desc, base_wfs, pool, refs, fn_a, fn_b)
        results.append(r)
        print_result(r)

    print_summary(results)
    return results


def run_realistic_name_tests():
    """Test with realistic workflow names — descriptive names spread better."""
    print_header("REALISTIC NAMES — descriptive workflow names (typical repo)")

    actions = ["actions/checkout@v4.0.0", "actions/setup-node@v4.0.0",
               "actions/cache@v4.0.0", "actions/upload-artifact@v4.0.0"]
    pool = {a: fake_sha() for a in actions}
    base_wfs = {}
    for name in REALISTIC_WORKFLOW_NAMES:
        base_wfs[f".github/workflows/{name}.yml"] = [random.choice(actions)]
    refs = {}

    new_pairs = [
        ("api-tests", "benchmark"), ("changelog", "compliance"),
        ("cost-report", "docs-preview"), ("feature-flags", "integration"),
        ("k8s-deploy", "load-test"), ("mobile-build", "notify-slack"),
        ("perf-test", "preview-env"), ("rebase-check", "smoke-test"),
        ("staging-deploy", "type-check"), ("validate-schema", "webhook-test"),
    ]

    results = []
    for a_name, b_name in new_pairs:
        r = run_global_scenario(
            f"{a_name}-vs-{b_name}",
            f"A adds {a_name}.yml, B adds {b_name}.yml",
            base_wfs, pool, refs,
            lambda w, p, r, n=a_name: w.__setitem__(
                f".github/workflows/{n}.yml", ["actions/checkout@v4.0.0"]),
            lambda w, p, r, n=b_name: w.__setitem__(
                f".github/workflows/{n}.yml", ["actions/setup-node@v4.0.0"]),
        )
        results.append(r)
        print_result(r)

    print_summary(results, "Realistic names — ")
    return results


def run_per_workflow_comparison():
    """Compare per-workflow lockfiles vs global."""
    print_header("PER-WORKFLOW LOCKFILES — one .lock per .yml")

    actions = ["actions/checkout@v4.0.0", "actions/setup-node@v4.0.0",
               "actions/cache@v4.0.0", "actions/upload-artifact@v4.0.0"]
    pool = {a: fake_sha() for a in actions}
    base_wfs = {}
    for name in REALISTIC_WORKFLOW_NAMES:
        base_wfs[f".github/workflows/{name}.yml"] = [random.choice(actions)]
    refs = {}

    scenarios = [
        ("both-add-diff-wfs", "Both add different workflows",
         lambda w, p, r: w.__setitem__(".github/workflows/api-tests.yml",
                                       ["actions/checkout@v4.0.0"]),
         lambda w, p, r: w.__setitem__(".github/workflows/smoke-test.yml",
                                       ["actions/setup-node@v4.0.0"])),
        ("both-add-same-wf", "Both add same workflow with different deps",
         lambda w, p, r: w.__setitem__(".github/workflows/api-tests.yml",
                                       ["actions/checkout@v4.0.0"]),
         lambda w, p, r: w.__setitem__(".github/workflows/api-tests.yml",
                                       ["actions/setup-node@v4.0.0"])),
        ("both-repin-checkout", "Both re-pin checkout to different SHAs",
         lambda w, p, r: repin_action(w, p, "actions/checkout"),
         lambda w, p, r: repin_action(w, p, "actions/checkout")),
        ("repin-vs-add", "One re-pins checkout, other adds new workflow",
         lambda w, p, r: repin_action(w, p, "actions/checkout"),
         lambda w, p, r: w.__setitem__(".github/workflows/smoke-test.yml",
                                       ["actions/setup-node@v4.0.0"])),
        ("repin-all-both", "Both re-pin ALL actions to different SHAs",
         lambda w, p, r: [p.__setitem__(k, fake_sha()) for k in list(p.keys())],
         lambda w, p, r: [p.__setitem__(k, fake_sha()) for k in list(p.keys())]),
    ]

    results = []
    for name, desc, fn_a, fn_b in scenarios:
        r = run_per_wf_scenario(name, desc, base_wfs, pool, refs, fn_a, fn_b)
        results.append(r)
        print_result(r)

    print_summary(results, "Per-workflow — ")
    return results


def run_union_merge_tests():
    """Test .gitattributes merge=union strategy."""
    print_header("UNION MERGE STRATEGY — .gitattributes merge=union")
    print("  ⚠️  Union merge avoids conflicts but may produce semantically")
    print("  invalid output (duplicate keys with different SHAs).\n")

    rng = random.Random(42)
    base_wfs, base_pool, refs = gen_base(100, rng)
    gitattr = ".github/workflows/actions.lock merge=union\n"

    scenarios = [
        ("disjoint-adds", "A adds wf 101-105, B adds wf 106-110",
         lambda w, p, r: add_wfs(w, p, r, range(101, 106)),
         lambda w, p, r: add_wfs(w, p, r, range(106, 111))),
        ("same-action-repin", "Both re-pin checkout → different SHAs",
         lambda w, p, r: repin_action(w, p, "actions/checkout"),
         lambda w, p, r: repin_action(w, p, "actions/checkout")),
        ("mixed-realistic", "A: +3wf repin 5 | B: +2wf -3wf repin 3",
         lambda w, p, r: (add_wfs(w, p, r, range(101, 104)), repin_wfs(w, p, range(1, 6))),
         lambda w, p, r: (add_wfs(w, p, r, range(104, 106)),
                          delete_wfs(w, [20, 30, 40]), repin_wfs(w, p, range(60, 63)))),
        ("massive-repin", "A re-pins ALL, B adds 10 wfs",
         lambda w, p, r: [p.__setitem__(k, fake_sha()) for k in list(p.keys())],
         lambda w, p, r: add_wfs(w, p, r, range(101, 111))),
    ]

    results = []
    for name, desc, fn_a, fn_b in scenarios:
        r = run_global_scenario(name, desc, base_wfs, base_pool, refs,
                                fn_a, fn_b, gitattributes=gitattr)
        results.append(r)
        print_result(r)

    print_summary(results, "Union merge — ")
    return results


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    random.seed(42)

    print("\n" + "=" * 80)
    print("  ACTIONS LOCKFILE MERGE CONFLICT ANALYSIS")
    print("  Evaluating git merge behavior for actions.lock across scenarios")
    print("=" * 80)

    all_results = {}
    all_results["stress"] = run_stress_tests()
    all_results["position"] = run_insertion_position_tests()
    all_results["realistic"] = run_realistic_name_tests()
    all_results["per_wf"] = run_per_workflow_comparison()
    all_results["union"] = run_union_merge_tests()

    # Final summary
    print_header("FINAL SUMMARY")

    for label, key in [
        ("Stress (100 wf, sequential names)", "stress"),
        ("Insertion position", "position"),
        ("Realistic names", "realistic"),
        ("Per-workflow lockfiles", "per_wf"),
        ("Union merge strategy", "union"),
    ]:
        valid = [r for r in all_results[key] if r is not None]
        clean = sum(1 for r in valid if not r.conflict)
        total = len(valid)
        pct = clean / total * 100 if total else 0
        bar = "█" * int(pct / 5) + "░" * (20 - int(pct / 5))
        print(f"  {label:40s} {bar} {clean}/{total} ({pct:.0f}%)")

    print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
