name: Happy path

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4.3.1
      - uses: nodeselector/actions-test-fixtures/nested-composite@updated

  build:
    uses: nodeselector/actions-test-fixtures/.github/workflows/reusable-build.yml@main

