name: Imposter commit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.1
      - uses: nodeselector/actions-test-fixtures/nested-composite@7b403c9ec14bd3ae0bbf793c2bee8815a7ac920b
