name: Imposter commit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.1
      # resolves to  https://gist.github.com/nodeselector/6c258af120b14da9a068e43f492922a4
      - uses: nodeselector/actions-test-fixtures/nested-composite@tampered
