on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true

jobs:
  call:
    uses: nodeselector/actions-test-fixtures/.github/workflows/reusable-build.yml@${{ inputs.ref }}
