name: nightly
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.3.1
      - name: setup-node
        uses: actions/setup-node@v5.0.0
      - name: download-artifact
        uses: actions/download-artifact@v4.1.8
