name: security
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5.0.0
      - name: scorecard-action
        uses: ossf/scorecard-action@v2.4.0
